FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl python3 build-base

RUN corepack enable && corepack prepare pnpm@9 

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV NODE_ENV=development

EXPOSE 3007

CMD ["node_modules/.bin/nodemon","index.js"]
